In [28]:
import mysql.connector as conn

In [29]:
mydb=conn.connect(host='localhost',user='root',password='@Born2Ride')

In [33]:
cursor=mydb.cursor()

In [31]:
cursor.execute('show databases')

In [32]:
cursor.fetchall()

[('breast_cancer',),
 ('classicmodels',),
 ('customer',),
 ('fun',),
 ('ineuron',),
 ('ineuron1',),
 ('ineuron_test',),
 ('information_schema',),
 ('mysql',),
 ('org',),
 ('performance_schema',),
 ('rohan12345',),
 ('sakila',),
 ('sudhanshu12345',),
 ('sys',),
 ('test12345',),
 ('world',)]

In [34]:
cursor.execute('create database cardataset') # we created car datase

In [35]:
cursor.fetchall()

[]

In [36]:
cursor.execute('create table cardataset.car(Price varchar(20), Maintaiace varchar(20),Doors varchar(20),Persons varchar(20),Luggage_boot varchar(20), Safety varchar(20), Class varchar(20))')

In [26]:
#cursor.execute('drop database CARDATASET')

In [27]:
#mydb.commit()

In [37]:
cursor.execute('use cardataset')

In [38]:
cursor.execute('show tables')

In [39]:
cursor.fetchall()  # we created table car

[('car',)]

In [42]:
sql = "INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s)"

In [43]:
import csv 
with open('car.data','r') as f:        #Dump all the data into database
    car_data = csv.reader(f,delimiter = '\n')
    for i in car_data:
        val = tuple(i[0].split(','))
        print(sql,val)
        cursor.execute(sql,val)

INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', '2', 'small', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', '2', 'small', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', '2', 'small', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', '2', 'med', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', '2', 'med', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', '2', 'med', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', '2', 'big', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', '2', 'big', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', '2', 'big', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', '4', 'small', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', '4', 'small', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', '4', 'small', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', '4', 'med', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', '4', 'med', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', '4', 'med', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', '4', 'big', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', '4', 'big', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', '4', 'big', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', 'more', 'small', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', 'more', 'small', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', 'more', 'small', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', 'more', 'med', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', 'more', 'med', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', 'more', 'med', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', 'more', 'big', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', 'more', 'big', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '2', 'more', 'big', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', '2', 'small', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', '2', 'small', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', '2', 'small', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', '2', 'med', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', '2', 'med', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', '2', 'med', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', '2', 'big', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', '2', 'big', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', '2', 'big', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', '4', 'small', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', '4', 'small', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', '4', 'small', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', '4', 'med', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', '4', 'med', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', '4', 'med', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', '4', 'big', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', '4', 'big', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', '4', 'big', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', 'more', 'small', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', 'more', 'small', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', 'more', 'small', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', 'more', 'med', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', 'more', 'med', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', 'more', 'med', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', 'more', 'big', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', 'more', 'big', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '3', 'more', 'big', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', '2', 'small', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', '2', 'small', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', '2', 'small', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', '2', 'med', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', '2', 'med', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', '2', 'med', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', '2', 'big', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', '2', 'big', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', '2', 'big', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', '4', 'small', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', '4', 'small', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', '4', 'small', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', '4', 'med', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', '4', 'med', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', '4', 'med', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', '4', 'big', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', '4', 'big', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', '4', 'big', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', 'more', 'small', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', 'more', 'small', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', 'more', 'small', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', 'more', 'med', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', 'more', 'med', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', 'more', 'med', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', 'more', 'big', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', 'more', 'big', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '4', 'more', 'big', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', '2', 'small', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', '2', 'small', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', '2', 'small', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', '2', 'med', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', '2', 'med', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', '2', 'med', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', '2', 'big', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', '2', 'big', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', '2', 'big', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', '4', 'small', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', '4', 'small', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', '4', 'small', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', '4', 'med', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', '4', 'med', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', '4', 'med', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', '4', 'big', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', '4', 'big', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', '4', 'big', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', 'more', 'small', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', 'more', 'small', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', 'more', 'small', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', 'more', 'med', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', 'more', 'med', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', 'more', 'med', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', 'more', 'big', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', 'more', 'big', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'vhigh', '5more', 'more', 'big', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'high', '2', '2', 'small', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'high', '2', '2', 'small', 'med', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'high', '2', '2', 'small', 'high', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'high', '2', '2', 'med', 'low', 'unacc')
INSERT INTO cardataset.car(Price, Maintaiace,Doors,Persons,Luggage_boot,Safety,Class) VALUES (%s, %s, %s, %s, %s, %s,%s) ('vhigh', 'high', '2', '2', 'med', 'med', 'unacc')

IndexError: list index out of range

In [44]:
mydb.commit()

In [ ]:
# check all the data is available or not

In [46]:
cursor.execute('select count(*) from cardataset.car')

In [47]:
cursor.fetchall()

[(1728,)]

In [ ]:
# Try to group all the data with Col1 and count occurence of each and every record based on col1 value

In [48]:
cursor.execute('select Price,count(*) from cardataset.car group by Price')

In [49]:
cursor.fetchall()

[('vhigh', 432), ('high', 432), ('med', 432), ('low', 432)]

In [50]:
cursor.execute('select Maintaiace,count(*) from cardataset.car group by Maintaiace')

In [51]:
cursor.fetchall()

[('vhigh', 432), ('high', 432), ('med', 432), ('low', 432)]

In [52]:
# Try to filter a record where column 3 value will be 4

In [59]:
cursor.execute('select Doors from cardataset.car where Doors=4')

In [60]:
cursor.fetchall()

[('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',),
 ('4',)]

In [61]:
# Try to update a column3 value with 8 wherever you have equal to 2

In [66]:
cursor.execute('select count(Doors) from cardataset.car where Doors=2')

In [67]:
cursor.fetchall()

[(432,)]

In [71]:
cursor.execute('update cardataset.car set Doors = "8" where Doors = "2"')

In [72]:
mydb.commit()

In [73]:
cursor.execute('select count(Doors) from cardataset.car where Doors = 8')

In [74]:
cursor.fetchall()

[(432,)]

In [75]:
# Delete the table

In [76]:
cursor.execute('drop table cardataset.car')
mydb.commit()

In [77]:
# checking it is dropped or not

In [78]:
cursor.execute('desc cardataset.car')

ProgrammingError: 1146 (42S02): Table 'cardataset.car' doesn't exist

In [79]:
# Delete the DAtabase

In [81]:
cursor.execute('drop database cardataset')

In [82]:
cursor.execute("show databases")

In [83]:
cursor.fetchall()

[('breast_cancer',),
 ('classicmodels',),
 ('customer',),
 ('fun',),
 ('ineuron',),
 ('ineuron1',),
 ('ineuron_test',),
 ('information_schema',),
 ('mysql',),
 ('org',),
 ('performance_schema',),
 ('rohan12345',),
 ('sakila',),
 ('sudhanshu12345',),
 ('sys',),
 ('test12345',),
 ('world',)]